version: '3'

services:
  database:
    image: 'mongo'
    container_name: 'rec_task_mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: caffeines
      MONGO_INITDB_ROOT_PASSWORD: pass2ord
      MONGO_INITDB_DATABASE: application
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  client:
    image: nginx
    ports:
        - 3000:80
    volumes:
        - ./client:/usr/share/nginx/html
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: application
    container_name: application
    restart: always
    env_file: .env
    ports:
        - 4000:4782
    volumes:
        - .:/home/application/app
        - /home/application/app/node_modules
    command: node app.js
    depends_on:
        - database